language: generic
os: osx
osx_image: xcode9.4

env:
  global:
    - secure: nKK5jhF4/Hk7TsGFKgWA3xEsjyCQhIxgaEsUV6ZsIXnl021Z9l3HeDmz6Hv2ZaHHYxo2fw3mGCXJnbmhApzEgX7XK/jUFGydIsMCpBUQfCodB83TRV5bOPQD++WdQaQQuZJTtcaNcVRi99bBVDnmBB+dMudAAo9rXTobQ9tNlobr6QfbCL7hjZ5sYiAsKfo2zv48gpcs8J5mT6SprlRn/Mn0ZtW/vEh7HUfOeKr8+s5vYcXcZLZ9jF7Xr7zn2c1pH7Xokf2tcKG2KO3Qvb6S9LjWJC85COlNn26hmrX7nRulwKAmL9qG8xEGkCZXSICChTjAnEYoM1RDgHSx7Xbe6snimB0tviVIrwOqSKGCtgxqyGpR9ftqbBTc4os6eeg/J2AAcvh20smJZEPxSfU1sjGpTt/H7H6Bt8a8pLu79Y6sDXDxFzJxQEDP0VgMKjFpT91NTwdj7Rt/20MlGqYJGH5Sym7m1ABdMkPOf3DbGJc6d08ZQmgPKo7XZ2HqHkoLyjtahR1dUl4prtxRsfRAt2OPnKjOSd1ngApf25rciG3nogunx/syvRQsEI9Y6uNf4FWunj57auf9n7peohKUDwnoBokNiYgHNKddVCIX8g12NxXc1VAEekQAdXU1RMgpB1EFgGPGBSi/1HnA2tFjct2ElXx+sltPMFZcH1g1mec=

script:
  - source ./.travis_scripts/build_all
