language: generic
os: osx
osx_image: xcode6.4
env:
  global:
  - secure: JEphGXJRvwaHWIvMlvDBzO4URA+lct0H93uOWwOQpVNBkD3aqfneErWyqnHZn0eqNGl96sJwCKuEPrJ3+66RsSFRUKDDnn0mZbLgFw2MRVdP8n1sJr/6apIyNqGVLGoKQ2bMDNP2LBw2QeIDU1kL25PhkndR0OOuwq51B0twCDFhnM7K8mHzpWB3MRyKV6gh7N1kLbKXo5EQVFmZiRRE+8x2isOlBFiig+kwxKxyS74qfelFhkuwCk7LtcF/Gl+3Rsqh1QJxYTECrhkEcnQyh9HLQyCMxl/KfdO9LtkA7x+Isitm2DlrSq+TmVCsEuhzRwxAIMjsNSA7mS2Cr5/HN/4C+ujLb0pyInPvfbNmgALhVcejTsm29yuPGAOOG3j5H2Bs5ZIMYMiBHaw4kPvyxjpcPoCwjkS+AEuBRtWTqmtUjMQnYAWXONNnW51P1KnHVkb8deqHC9nrCq62awO8skC5+DBtzYPUlbiO35Ehy3Mj7/5pgtZ+QXWiE1mWvDJd/YLQZ4SH/z0vGsJDJ2ESwDTbQpUKODmFC5qx44mLuaLgpZ21tjT3L9OcW6hU+RC0qEzJxEiu5yEgTGizpudUSoF5A58eC9MRH/9Rf6WNL+ClyLTL1tNE4kjxYbtYDjKbhAlR9/jHDq1svKsluqq8ltlywKqg9ZOUg3fqczh+yN8=
  matrix:
    - PY_CONDITION="python >=2.7,<3"
    - PY_CONDITION="python >=3.5,<3.6"
    - PY_CONDITION="python >=3.6"
before_install:
  # Remove homebrew.
  - |
    echo ""
    echo "Removing homebrew from Travis CI to avoid conflicts."
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
    chmod +x ~/uninstall_homebrew
    ~/uninstall_homebrew -fq
    rm ~/uninstall_homebrew
install:
  # Install Miniconda.
  - |
    echo ""
    echo "Installing a fresh version of Miniconda."
    MINICONDA_URL="https://repo.continuum.io/miniconda"
    MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
    curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
    bash $MINICONDA_FILE -b
  # Configure conda.
  - |
    echo ""
    echo "Configuring conda."
    source /Users/travis/miniconda3/bin/activate root
    conda config --remove channels defaults
    conda config --add channels defaults
    conda config --add channels conda-forge
    conda config --add channels mcs07
    conda config --set show_channel_urls true
    conda install --yes --quiet conda-build-all
    conda install --yes --quiet conda-forge-build-setup
    source run_conda_forge_build_setup
script:
  - conda build-all ./recipes --inspect-channels mcs07 --upload-channels mcs07 --matrix-condition "numpy >=1.11" "$PY_CONDITION" "r-base >=3.3.2"
