language: generic
os: osx
osx_image: xcode6.4

env:
  global:
  - secure: nKK5jhF4/Hk7TsGFKgWA3xEsjyCQhIxgaEsUV6ZsIXnl021Z9l3HeDmz6Hv2ZaHHYxo2fw3mGCXJnbmhApzEgX7XK/jUFGydIsMCpBUQfCodB83TRV5bOPQD++WdQaQQuZJTtcaNcVRi99bBVDnmBB+dMudAAo9rXTobQ9tNlobr6QfbCL7hjZ5sYiAsKfo2zv48gpcs8J5mT6SprlRn/Mn0ZtW/vEh7HUfOeKr8+s5vYcXcZLZ9jF7Xr7zn2c1pH7Xokf2tcKG2KO3Qvb6S9LjWJC85COlNn26hmrX7nRulwKAmL9qG8xEGkCZXSICChTjAnEYoM1RDgHSx7Xbe6snimB0tviVIrwOqSKGCtgxqyGpR9ftqbBTc4os6eeg/J2AAcvh20smJZEPxSfU1sjGpTt/H7H6Bt8a8pLu79Y6sDXDxFzJxQEDP0VgMKjFpT91NTwdj7Rt/20MlGqYJGH5Sym7m1ABdMkPOf3DbGJc6d08ZQmgPKo7XZ2HqHkoLyjtahR1dUl4prtxRsfRAt2OPnKjOSd1ngApf25rciG3nogunx/syvRQsEI9Y6uNf4FWunj57auf9n7peohKUDwnoBokNiYgHNKddVCIX8g12NxXc1VAEekQAdXU1RMgpB1EFgGPGBSi/1HnA2tFjct2ElXx+sltPMFZcH1g1mec=
  matrix:
    - PY_CONDITION="python >=2.7,<3"
    - PY_CONDITION="python >=3.5,<3.6"
    - PY_CONDITION="python >=3.6"

before_install:
  # Remove homebrew.
  - |
    echo ""
    echo "Removing homebrew from Travis CI to avoid conflicts."
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
    chmod +x ~/uninstall_homebrew
    ~/uninstall_homebrew -fq
    rm ~/uninstall_homebrew

install:
  # Install Miniconda.
  - |
    echo ""
    echo "Installing a fresh version of Miniconda."
    MINICONDA_URL="https://repo.continuum.io/miniconda"
    MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
    curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
    bash $MINICONDA_FILE -b -p $HOME/conda
  # Configure conda.
  - |
    echo ""
    echo "Configuring conda."
    export PATH="$HOME/conda/bin:$PATH"
    export CPU_COUNT=2
    export PYTHONUNBUFFERED=1
    export MACOSX_DEPLOYMENT_TARGET="10.9"
    conda config --remove channels defaults
    conda config --add channels defaults
    conda config --add channels conda-forge
    conda config --add channels mcs07
    conda config --set show_channel_urls true
    conda config --set auto_update_conda false
    conda config --set add_pip_as_python_dependency false
    conda update --yes --quiet conda conda-env conda-build
    conda install --yes --quiet jinja2 anaconda-client=1.6.5
    conda install --yes --quiet conda-build=2
    conda install --yes --quiet conda-build-all
    conda info
    conda config --get

script:
  - conda build-all ./recipes --inspect-channels mcs07 --upload-channels mcs07 --matrix-condition "numpy >=1.11" "$PY_CONDITION" "r-base >=3.3.2"
