environment:
  BINSTAR_TOKEN:
    secure: YJa9B6I4KDmsY9+HAZYnx//O60W1Majef1mN2z+UU4qJDEzVyDw44ppEjlLgffUu
  CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
  matrix:
    - PLATFORM: "64"

platform:
  - x64

install:
  - cmd: set CONDA_NPY=19
  - cmd: rmdir C:\cygwin /s /q
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda.exe config --add channels conda-forge
  - cmd: conda.exe config --add channels mcs07
  - cmd: conda.exe config --set show_channel_urls true
  - cmd: appveyor-retry conda.exe update --yes --quiet conda
  - cmd: appveyor-retry conda.exe install --yes --quiet conda-forge-pinning conda-forge-ci-setup=1.* networkx anaconda-client
  - cmd: appveyor-retry run_conda_forge_build_setup
  - cmd: conda.exe info
  - cmd: conda.exe config --get

build: off

test_script:
  - python .ci_support\build_all.py recipes --arch %PLATFORM%
