{% set name = "tesserocr" %}
{% set version = "2.2.2" %}
{% set sha256 = "f245c85643acaa6c740885c2cb18c6ca2ddb569756fbdeb10bd85a08c0a9fff2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - tesseract4beta.patch  # Workaround for bug in tesseract 4 beta. Has been fixed in tesseract master.
    - tesseract4beta2.patch  # Upstream commit from tesserocr master.

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - cython
    - tesseract 4.*
  run:
    - python
    - tesseract 4.*

test:
  imports:
    - tesserocr

about:
  home: https://github.com/sirfz/tesserocr
  summary: "A simple, Pillow-friendly, Python wrapper around tesseract-ocr API using Cython"
  license: MIT
