{% set name = "tesserocr" %}
{% set version = "2.2.2" %}
{% set sha256 = "f245c85643acaa6c740885c2cb18c6ca2ddb569756fbdeb10bd85a08c0a9fff2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - tesseract
  run:
    - python
    - tesseract

test:
  imports:
    - tesserocr

about:
  home: https://github.com/sirfz/tesserocr
  summary: "A simple, Pillow-friendly, Python wrapper around tesseract-ocr API using Cython"
  license: MIT
