{% set name = "tesserocr" %}
{% set version = "2.3.1" %}
{% set sha256 = "72ac9b6bd2c6b76c9c512494824d3d741bc314abbf2ae9b91d128ba81fdffd11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython
    - python
    - pip
    - tesseract
  run:
    - python
    - tesseract

test:
  imports:
    - tesserocr

about:
  home: https://github.com/sirfz/tesserocr
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple, Pillow-friendly, Python wrapper around tesseract-ocr API using Cython'
  doc_url: https://github.com/sirfz/tesserocr
  dev_url: https://github.com/sirfz/tesserocr


extra:
  recipe-maintainers:
    - mcs07
