{% set name = "tesserocr" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba60466fc91835656d4b4f93deb4ba7543d1588722ec4e0b84cc694500373b85

build:
  number: 1
  skip: True  # [win and vc<14]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython
    - leptonica
    - python
    - pip
    - tesseract 3.*
  run:
    - python

test:
  imports:
    - tesserocr

about:
  home: https://github.com/sirfz/tesserocr
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple, Pillow-friendly, Python wrapper around tesseract-ocr API using Cython'
  doc_url: https://github.com/sirfz/tesserocr
  dev_url: https://github.com/sirfz/tesserocr


extra:
  recipe-maintainers:
    - mcs07
