version: 2

jobs:
  build:
    docker:
      - image: condaforge/linux-anvil
    branches:
      only:
        - master
    steps:
      - run:
          command: ls
      - run:
          command: pwd
      - run:
          command: bash .CI/circleci_build.sh
