version: 2

jobs:
  build:
    working_directory: ~/test
    machine: true
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          command: ./.circleci/run_docker_build.sh
