{% set name = "tclap" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/tclap/files/tclap-{{ version }}.tar.gz
  sha256: f5013be7fcaafc69ba0ce2d1710f693f61e9c336b6292ae4f57554f59fde5837

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}

about:
  home: http://tclap.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Templatized C++ Command Line Parser Library.'
  doc_url: http://tclap.sourceforge.net/manual.html

extra:
  recipe-maintainers:
    - mcs07
