{% set name = "InChI" %}
{% set version = "1.05" %}
{% set sha256 = "4ac311ca3a16fa75d695ec4fc711e74045c6d6c882dea0dd1055961fba643720" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: INCHI-1-SRC.zip
  url: http://www.inchi-trust.org/download/105/INCHI-1-SRC.zip
  sha256: {{ sha256 }}
  patches:
    - afxres.patch  # [win]

build:
  number: 0
  skip: True  # [osx]
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]

requirements:
  build:
    - vc 9  # [win and py27]
    - vc 14  # [win and py>=35]
  run:
    - vc 9  # [win and py27]
    - vc 14  # [win and py>=35]

test:
  commands:
    - inchi-1

about:
  home: http://www.inchi-trust.org/
  license: IUPAC/InChI-Trust InChI Licence No. 1.0
  license_file: LICENCE
  summary: 'IUPAC InChI open-source chemical structure representation algorithm'

extra:
  recipe-maintainers:
    - mcs07
