{% set name = "ChemSpiPy" %}
{% set version = "1.0.5" %}
{% set sha256 = "4dddcdf725245f1cf77ec040a6103648c98f46e11c24aded78ae1379c79bcf56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - lxml
    - requests
    - six
  run:
    - python
    - lxml
    - requests
    - six

test:
  imports:
    - chemspipy

about:
  home: https://github.com/mcs07/ChemSpiPy
  license: MIT
  license_file: LICENSE
  summary: 'Python wrapper for the ChemSpider API'
  doc_url: http://chemspipy.readthedocs.io
  dev_url: https://github.com/mcs07/ChemSpiPy
