{% set name = "tesseract" %}
{% set version = "3.05.00" %}
{% set sha256 = "3fe83e06d0f73b39f6e92ed9fc7ccba3ef734877b76aa5ddaaa778fac095d996" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/tesseract-ocr/tesseract/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - cmake
    - libpng
    - jpeg
    - libtiff
    - zlib
    - leptonica
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - libpng
    - jpeg
    - libtiff
    - zlib
    - leptonica
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    - tesseract --help

about:
  home: https://github.com/tesseract-ocr/tesseract
  license: Apache License 2.0
  summary: Open Source OCR Engine
