{% set name = "tesseract" %}
{% set version = "4.0.0" %}
{% set sha256 = "a1f5422ca49a32e5f35c54dee5112b11b99928fc9f4ee6695cdc6768d69f61dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/tesseract-ocr/{{ name }}/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
    folder: tesseract
    patches:
      # Install gettimeofday.h header to include directory
      - gettimeofday.patch  # [win]
      # Rename timezone struct to avoid name clash
      - timezone.patch  # [win]
  - url: https://github.com/tesseract-ocr/tessdata_fast/archive/4.0.0.tar.gz
    sha256: f1b71e97f27bafffb6a730ee66fd9dc021afc38f318fdc80a464a84a519227fe
    folder: tessdata_fast

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - pkg-config  # [not win]
    - cmake  # [win]
  host:
    - giflib  # [not win]
    - jpeg
    - leptonica
    - libpng
    - libtiff
    - libwebp
    - openjpeg
    - xz  # [not win]
    - zlib
  run:
    - giflib  # [not win]
    - jpeg
    - leptonica
    - libpng
    - libtiff
    - libwebp
    - openjpeg
    - xz  # [not win]
    - zlib

test:
  commands:
    - tesseract --help

about:
  home: https://github.com/tesseract-ocr/tesseract
  license: Apache-2.0
  license_family: Apache
  license_file: tesseract/LICENSE
  summary: Open Source OCR Engine
  doc_url: https://github.com/tesseract-ocr/tesseract
  dev_url: https://github.com/tesseract-ocr/tesseract

extra:
  recipe-maintainers:
    - mcs07
