{% set name = "perl" %}
{% set base_version = "5.22.2" %}
{% set version = base_version + ".1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ base_version }}.tar.gz  # [unix]
  fn:  strawberry-{{ name }}-{{ version }}-32bit-portable.zip  # [win]
  url: http://www.cpan.org/src/5.0/{{ name }}-{{ base_version }}.tar.gz  # [unix]
  url:  http://strawberryperl.com/download/{{ version }}/strawberry-{{ name }}-{{ version }}-32bit-portable.zip  # [win]
  sha256: 81ad196385aa168cb8bd785031850e808c583ed18a7901d33e02d4f70ada83c2  # [unix]
  sha256: c599c88906bb1955fdc45a00dccd78b8c327ed6f7010185cb2e9bacf590574d2  # [win]

build:
  skip: True  # [not linux]
  number: 0

test:
  commands:
    - perl --help

about:
  home: http://www.perl.org/
  license: Artistic License
  license_family: Other
  license: Perl
  summary: "The Perl programming language interpreter."
