{% set name = "mahotas" %}
{% set version = "1.4.3" %}
{% set sha256 = "e113fb73f1f717f1a9124b41496b030628efb72a23b0150a42ecb18b08b030c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win and py35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - python
    - numpy x.x
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  imports:
    - mahotas

about:
  home: http://mahotas.readthedocs.io/
  license: MIT
  summary: Computer vision and image processing library for Python
  dev_url: https://github.com/luispedro/mahotas
