{% set name = "leptonica" %}
{% set version = "1.77.0" %}
{% set sha256 = "161d0b368091986b6c60990edf257460bdc7da8dd18d48d4179e297bcdca5eb7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/DanBloomberg/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - cmake.patch  # [win]

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("leptonica", max_pin="x.x") }}

# TODO: conda-forge giflib missing headers on windows?

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - m4  # [not win]
    - pkg-config  # [not win]
    - cmake  # [win]
  host:
    - giflib  # [not win]
    - jpeg
    - libpng
    - libtiff
    - libwebp
    - openjpeg
    - xz
    - zlib
  run:
    - giflib  # [not win]
    - jpeg
    - libpng
    - libtiff
    - libwebp
    - openjpeg
    - xz
    - zlib

test:
  commands:
    - convertfilestopdf --help 2>&1 | grep 'resolution' &> /dev/null  # [not win]

about:
  home: https://github.com/DanBloomberg/leptonica
  license: BSD 2-Clause
  license_family: BSD
  license_file: leptonica-license.txt
  summary: Leptonica image processing library
  doc_url: http://www.leptonica.org/
  dev_url: https://github.com/DanBloomberg/leptonica

extra:
  recipe-maintainers:
    - mcs07
