{% set name = "leptonica" %}
{% set version = "1.74.4" %}
{% set sha256 = "29c35426a416bf454413c6fec24c24a0b633e26144a17e98351b6dffaa4a833b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/DanBloomberg/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - cmake.patch  # [win]
    - optimize.patch  # [win and py27]

build:
  number: 0
  skip: True  # [win and py>35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - automake  # [not win]
    - libtool  # [not win]
    - pkg-config  # [not win]
    - cmake  # [win]
    - jpeg
    - libpng
    - libtiff
    - zlib
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - jpeg
    - libpng
    - libtiff
    - zlib
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    - convertfilestopdf --help 2>&1 | grep 'resolution' &> /dev/null  # [not win]

about:
  home: https://github.com/DanBloomberg/leptonica
  license: FreeBSD 2-clause license
  summary: Leptonica image processing library
